"""Khoi phuc database

Revision ID: 41857d56ac99
Revises: 02b2832f531a
Create Date: 2026-05-06 17:03:28.503465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41857d56ac99'
down_revision: Union[str, Sequence[str], None] = '02b2832f531a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sanpham', sa.Column('ID_HinhAnh', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sanpham', 'anhsp', ['ID_HinhAnh'], ['ID_HinhAnh'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sanpham', type_='foreignkey')
    op.drop_column('sanpham', 'ID_HinhAnh')
    # ### end Alembic commands ###
